version: "3"
services:

  potato:
    image: postgres:11.5-alpine
    ports:
      - 5432-5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password1}

  apple:
    image: postgres:11.5-alpine
    ports:
      - 5434-5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password1}